//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class answer_response
    {
        public int id { get; set; }
        public int surveyID { get; set; }
        public Nullable<int> id_users { get; set; }
        public Nullable<int> id_sv { get; set; }
        public Nullable<int> id_ctdt { get; set; }
        public string json_answer { get; set; }
        public int time { get; set; }
    
        public virtual ctdt ctdt { get; set; }
        public virtual sinhvien sinhvien { get; set; }
        public virtual survey survey { get; set; }
        public virtual users users { get; set; }
    }
}
